mydata<-read.table(file="美食餐馆食客评分数据.txt",header=TRUE,sep=" ",stringsAsFactors = FALSE)
View(mydata)
cor(mydata$taste,mydata$score_avg,method="pearson")
par(mfrow=c(1,2),mar=c(6,4,4,4))
plot(mydata$taste,mydata$score_avg,main = "口味打分和平均打分的散点图",xlab="口味打分",ylab="平均打分",cex.main=0.8,cex.lab=0.8)
plot(mydata$taste,mydata$score_avg,main = "口味打分和平均打分的散点图(带回归线)",xlab="口味打分",ylab="平均打分",cex.main=0.8,cex.lab=0.8)
mo<-lm(mydata$score_avg~mydata$taste)
abline(mo$coefficients,col=2)
m.Loess<-loess(score_avg~taste,data=mydata)
Ord<-order(mydata$taste)
lines(mydata$taste[Ord],m.Loess$fitted[Ord],lwd=1,lty=2,col=2)
library("scatterplot3d")
par(mfrow=c(1,2),mar=c(6,4,4,4))
scatterplot3d(mydata$taste,mydata$score_avg,mydata$cost_avg,main="美食餐馆口味打分、平均打分和人均消费的平均散点图",xlab="口味打分",ylab="平均打分",zlab="人均消费金额",cex.main=0.8,cex.lab=0.8,cex.axis=0.8)
symbols(mydata$taste,mydata$score_avg,circle=mydata$cost_avg,inches=0.2,main="美食餐馆口味打分、平均打分和人均消费的气泡图",xlab="口味打分",ylab="平均打分",cex.main=0.8,cex.lab=0.8,cex.axis=0.8,fg="white",bg="lightblue")
library("corrgram")
corrgram(mydata[,5:9],lower.panel=panel.shade,upper.panel=panel.pie,text.panel=panel.txt,main="美食餐馆打分和人均消费的相关系数图")
corrgram(mydata[,5:9],lower.panel=panel.ellipse,upper.panel=panel.pts,diag.panel=panel.minmax,main="美食餐馆打分和人均消费的相关系数图")

