setwd("./课程数据集")
MyData<-read.table(file = "美食餐馆食客评分数据.txt",header = TRUE,sep = " ",stringsAsFactors = FALSE)
(CrossT<-table(MyData$food_type,MyData$region))
addmargins(CrossT)
addmargins(round(prop.table(CrossT,1)*100,2),2)
addmargins(round(prop.table(CrossT,2)*100,2),1)
addmargins(round(prop.table(CrossT)*100,2))
library("gmodels")
CrossTable(MyData$food_type,MyData$region)
library("vcd")
assocstats(CrossT)
mosaicplot(~food_type+region,data=MyData,main="主打菜和区域的马克赛图")
cor(MyData$heat,MyData$cost_avg,method="spearman")
cor(MyData$heat,MyData$score_avg,method="kendall")
